- name: Loops demo
  hosts: localhost
  tasks:
    - name: Print fruit name
      debug:
        msg: fruit name - Apple

    - name: Print multiple fruit names using loop
      debug:
        msg: fruit name - {{ item }} #item is default, here used to call the fruit names in loop
      loop:
        - Apple
        - banana
        - coconut

    - name: Print multiple fruit names with quantity
      debug:
        msg: fruit name - {{ item.name }} and quantity is {{ item.quantity }}
      loop:
        - { name: "Apple", quantity: 10 }
        - { name: "Banana", quantity: 11 }
        - { name: "Coconut", quantity: 15 }