- name: Play Variables
  hosts: localhost
  vars:          #declaring a variable
    url: play.example.com
  tasks:
    - name: Play Variable Example
      ansible.builtin.debug:
        msg: url= {{ url }}   #accessing a variable

- name: Play Variables from file
  hosts: localhost
  vars_files:          #declaring a variable and vars_file can only accessible at play level
    - var.yml
  tasks:
    - name: Play Variable Example from File
      ansible.builtin.debug:
        msg: url= {{ url }}   #accessing a variable

- name: Play Variables Task Level
  hosts: localhost
  tasks:
    - name: Play Variable Example
      vars:
        url: play.example.com  #Task level variables can only accessible in this task but not for other tasks
      ansible.builtin.debug:
        msg: url= {{ url }}   #accessing a variable

- name: Play Variables from Inventory
  hosts: all
  tasks:
    - name: Play Variable from Inventory
      ansible.builtin.debug:
        msg: url= {{ url }}   #accessing a variable


##we can also declare variable from cmd line(CLI) by adding it to cmd
##Variable precedence: cli variable, task level variables, variables from file, play level variable, inventory variables

- name: Play Variables of Predefined Ansible Variable
  hosts: all
  tasks:
    - name: Play Variable from Inventory
      ansible.builtin.debug:
        msg: "url= {{ url }}, Hostname of server= {{ansible_hostname}}" #ansible has some pre defined variable eg: ansible_hostname and we no need to declare them

- name: Register a Variable
  hosts: localhost
  tasks:
    - name: Register a Variable
      ansible.builtin.shell: uptime
      register: out

    - name: Print out
      ansible.builtin.debug:
        msg: {{ out }}